version: '3'

services:
  app:
    image: app:dev
    container_name: app_container
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://mongo_container:27017/mydatabase"
    volumes:
      - .:/usr/src/app
    networks:
      - fresh_network

  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"  # Map port 27017 from the container to the host
    networks:
      - fresh_network

networks:
  fresh_network:
    driver: bridge
